name: Frontend Vue CI/CD Pipeline

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'src/frontend-src/**'
  pull_request:
    branches: [ "develop" ]
    paths:
      - 'src/frontend-src/**'

jobs:
  frontend:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
        cd src/frontend-src
        npm install
    - name: Lint and Test
      run: |
        cd src/frontend-src
        npm run test:unit
    - name: Build
      run: |
        cd src/frontend-src
        npm run build
